apiVersion: apps/v1
kind: Deployment
metadata:
  name: "nodeserver"
  labels:
    app: "nodeserver"
spec:
  selector:
    matchLabels:
      app: "nodeserver"
  replicas: 10
  template:
    metadata:
      labels:
        app: "nodeserver"
    spec:
      containers:
        - name: nodeserver
          image: "gpmarchi/http-server:v4"
          envFrom:
            - configMapRef:
                name: nodeserver-env
