apiVersion: apps/v1
kind: Deployment
metadata:
  name: "nodeserver"
  labels:
    app: "nodeserver"
spec:
  selector:
    matchLabels:
      app: "nodeserver"
  replicas: 1
  template:
    metadata:
      labels:
        app: "nodeserver"
    spec:
      containers:
        - name: nodeserver
          image: "gpmarchi/http-server:v14"

          resources:
            requests:
              cpu: "0.05"
              memory: 20Mi
            limits:
              cpu: "0.05"
              memory: 25Mi

          startupProbe:
            httpGet:
              path: /healthz
              port: 3333
            periodSeconds: 3
            failureThreshold: 30
            timeoutSeconds: 1
            successThreshold: 1

          readinessProbe:
            httpGet:
              path: /healthz
              port: 3333
            periodSeconds: 3
            failureThreshold: 1
            timeoutSeconds: 1
            successThreshold: 1

          livenessProbe:
            httpGet:
              path: /healthz
              port: 3333
            periodSeconds: 5
            failureThreshold: 1
            timeoutSeconds: 1
            successThreshold: 1

          envFrom:
            - configMapRef:
                name: nodeserver-env
            - secretRef:
                name: nodeserver-secret
          volumeMounts:
            - mountPath: "/app/myfamily"
              name: config
              readOnly: true
            - mountPath: "/node/pvc"
              name: nodeserver-volume

      volumes:
        - name: nodeserver-volume
          persistentVolumeClaim:
            claimName: nodeserver-pvc

        - name: config
          configMap:
            name: configmap-family
            items:
              - key: members
                path: "family.txt"
